pipeline {
    agent any
    stages {
        stage('Build image') {
            steps {
                echo 'Starting to build docker image'
                dir("hw17") {
                    sh "pwd"
                }

                script {
                    workerImage = docker.build("worker-img", "-f worker.Dockerfile .")
                }
            }
        }
    }
}
