pipeline {
    agent any
    stages {
        stage('Build image') {
            steps {
                echo 'Starting to build docker image'

                script {
                    workerImage = docker.build("worker-img", "-f worker.Dockerfile .")
                }
            }
        }
    }
}
