global:
  resolve_timeout: 10s

route:
  group_by: ['alertname']
  group_wait: 3s
  receiver: 'telegram-bot'

receivers:
- name: 'telegram-bot'
  telegram_configs:
  - bot_token: ${TELEGRAM_TOKEN}
    api_url: 'https://api.telegram.org'
    chat_id: ${CHAT_ID}
    parse_mode: "HTML"

